micronaut:
  application:
    name: resourceinventory
  server:
    port: 8182
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

endpoints:
  health:
    enabled: true
    sensitive: false
    url:
      enabled: true
  metrics:
    enabled: true
    sensitive: false